### ISSUE TITLE
add Cryptopia

### ISSUE THREAD

**Issue by basnijholt** [basnijholt/crypto-bot#2]
```bash
In [1]: import exchange

In [2]: exchange.get_exchange('Cryptopia')
Out[2]: <ccxt.cryptopia.cryptopia at 0x111d45198>

In [3]: c = exchange.get_exchange('Cryptopia')

In [4]: exchange.buy(c, 'NAV', 0.01)
2018-01-17 10:41.41 exception executing buy order
Traceback (most recent call last):
  File "/Users/basnijholt/Seafile/Work/crypto-bot/exchange.py", line 82, in buy
    order = client.create_market_buy_order(symbol, amount, params)
  File "/Users/basnijholt/miniconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1022, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "/Users/basnijholt/miniconda3/lib/python3.6/site-packages/ccxt/cryptopia.py", line 351, in create_order
    raise ExchangeError(self.id + ' allows limit orders only')
ccxt.base.errors.ExchangeError: cryptopia allows limit orders only
---------------------------------------------------------------------------
ExchangeError                             Traceback (most recent call last)
<ipython-input-4-66a2ceb55289> in <module>()
----> 1 exchange.buy(c, 'NAV', 0.01)

~/Seafile/Work/crypto-bot/exchange.py in buy(client, ticker, dollars)
     80
     81     try:
---> 82         order = client.create_market_buy_order(symbol, amount, params)
     83     except Exception:
     84         logger.critical('exception executing buy order', exc_info=True)

~/miniconda3/lib/python3.6/site-packages/ccxt/base/exchange.py in create_market_buy_order(self, symbol, amount, params)
   1020
   1021     def create_market_buy_order(self, symbol, amount, params={}):
-> 1022         return self.create_order(symbol, 'market', 'buy', amount, None, params)
   1023
   1024     def create_market_sell_order(self, symbol, amount, params={}):

~/miniconda3/lib/python3.6/site-packages/ccxt/cryptopia.py in create_order(self, symbol, type, side, amount, price, params)
    349     def create_order(self, symbol, type, side, amount, price=None, params={}):
    350         if type == 'market':
--> 351             raise ExchangeError(self.id + ' allows limit orders only')
    352         self.load_markets()
    353         market = self.market(symbol)

ExchangeError: cryptopia allows limit orders only
```

**Comment by basnijholt** [comment]
cryptopia doesn't exist anymore
